import Head from 'next/head'
import AnimateBackgroundTwo from '../components/AnimateBackgroundTwo'
import AnimateBackground from '../components/AnimateBackground'
import Homepage from '../components/Homepage'


export default function Home() {
  return (
    <>
      <Head>
        <title>Jon Doe Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      
        <div className="relative w-full h-screen bg-black overflow-hidden ">
          
        <div className="max-w-screen-2xl h-full mx-auto flex justify-center items-center">
          <Homepage/>
        </div>
          

          <AnimateBackground/>
          <AnimateBackgroundTwo/>

        </div>
      </main>
    </>
  )
}
